[project]
name = "template-python-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastembed>=0.6.1",
    "loguru>=0.7.3",
    "pre-commit>=4.5.1",
    "qdrant-client[fastembed]>=1.14.2",
    "requests>=2.32.5",
]

[project.scripts]
qdrant-check = "src.utils.qdrant.inspect_db:main"

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.mypy]
explicit_package_bases = true
ignore_missing_imports = true
namespace_packages = true

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
# Reglas que quieres activar
select = [
    "E",
    "F",
    "I",
    "W",
    "UP",
    "N",
    "B",
    "C4",
]

ignore = [
    "E501",
]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2
